defaults: &defaults
  jira:
    username: "maxim.meresenschi@saltedge.com"
    token: "ATATT3xFfGF0bRU1Bgpaf4NgwZ_THo52sVNw99jIRGEzS5BnmdbaqMpZy7eIjSc78mNTcHxKxcGl7NKYI7gfvPiSLLdOYXrg_p6eP0LaOVQZwRdfB0Tb4trqv6ZkPbZOvDR-sd1KFIQW68ZetBBqpBgdo4aAlJ-vJQGphJkwtAgXxMSFEvdz3eg=FE605D58"

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
